# Basic configuration to get started.

########## KijiREST Configuration ##########
# The cluster property defines the URI of the Kiji cluster.
# All instances on the cluster are surfaced to clients.

cluster: "kiji://.env/"
cors: false
cacheTimeout: 10 # default amount of time in minutes to wait before clearing cache of instances and tables.
freshening:
  freshen: true          # whether to freshen columns by default
  timeout: 100           # default amount of time in ms to wait for freshening to finish
service-discovery: true  # whether to register this REST instance with service discovery
remote-shutdown: true    # enable/disable admin command that allows the server to be shut down via REST


########## Dropwizard Configuration ##########
# Set default port and path to REST URI and let logs divert to ./logs/ instead of
# printing to the console. This is recommended for production systems. For more
# information on Dropwizard logging options and defaults, see
# http://dropwizard.codahale.com/manual/core/#configuration-defaults

http:
  port: 8080
  adminPort: 8081
  requestLog:
    console:
      # If true, log requests to stdout.
      enabled: false
      timeZone: UTC
      logFormat: null
    file:
      enabled: true
      timeZone: UTC
      logFormat: null
      currentLogFilename: ./logs/requests.log
      archive: true
      archivedLogFilenamePattern: ./logs/requests-%d.log.gz
      archivedFileCount: 5
logging:
  console:
    enabled: false
    threshold: ALL
    timeZone: UTC
    logFormat: null
  file:
    enabled: true
    threshold: ALL
    timeZone: UTC
    logFormat: null
    currentLogFilename: ./logs/app.log
    archive: true
    archivedLogFilenamePattern: ./logs/app-%d.log.gz
    archivedFileCount: 5
